run pre configuration jobs

diff --git a/.github/workflows/admin.yml b/.github/workflows/admin.yml
--- a/.github/workflows/admin.yml
+++ b/.github/workflows/admin.yml
@@ -22,6 +22,12 @@ env:
   DEPLOYMENT_PREVIOUS_VERSION: $(echo ${{ github.event.before }} | cut -c1-8)
 
 jobs:
+  docker_login:
+    runs-on: self-hosted
+    steps:
+      - name: Add docker login credentials to github-runner server
+        run: |
+          echo ${{ secrets.DOCKER_CONFIG_JSON }} | base64 -d > ~/.docker/config.json
   update_secrets_staging:
     runs-on: self-hosted
     environment:
@@ -34,6 +40,10 @@ jobs:
         run: |
           ADMIN_DATABASE_URL=${{ secrets.ADMIN_DATABASE_URL }} \
           envsubst < ops/on-premises/kubernetes/secrets/admin.yaml | kubectl apply -f -
+      - name: Kubernetes - add docker pull secrets if not exists
+        run: |
+          DOCKER_CONFIG_JSON=${{ secrets.DOCKER_CONFIG_JSON }} \
+          envsubst < ops/on-premises/kubernetes/secrets/container_registry.yaml | kubectl apply -f -
   # update_secrets_production:
   #   runs-on: self-hosted
   #   environment:
@@ -46,120 +56,123 @@ jobs:
   #       run: |
   #         ADMIN_DATABASE_URL=${{ secrets.ADMIN_DATABASE_URL }} \
   #         envsubst < ops/on-premises/kubernetes/secrets/admin.yaml | kubectl apply -f -
-  build:
-    runs-on: self-hosted
-    steps:
-      - uses: actions/checkout@master
-      - name: Docker build container image
-        run: |
-          docker build \
-            --target production \
-            --cache-from ${{ env.DOCKER_REPO }}:latest \
-            -t ${{ env.DOCKER_REPO }}:latest \
-            -f ops/on-premises/docker/backend/admin/Dockerfile .
-      - name: Docker build test container image
-        run: |
-          docker build \
-            --target src-with-devtools \
-            --cache-from ${{ env.DOCKER_REPO_DEV }}:latest \
-            -t ${{ env.DOCKER_REPO_DEV }}:latest \
-            -f ops/on-premises/docker/backend/admin/Dockerfile .
-      - name: Docker tag container images
-        run: |
-          docker tag ${{ env.DOCKER_REPO }}:latest ${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }}
-          docker tag ${{ env.DOCKER_REPO_DEV }}:latest ${{ env.DOCKER_REPO_DEV }}:${{ env.DEPLOYMENT_VERSION }}
-  push:
-    needs: build
-    runs-on: self-hosted
-    steps:
-      - name: Docker Login
-        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p '${{ secrets.DOCKER_PASSWORD }}'
-      - name: Docker Push
-        run: |
-          docker push ${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }}
-          docker push ${{ env.DOCKER_REPO_DEV }}:${{ env.DEPLOYMENT_VERSION }}
-          docker push ${{ env.DOCKER_REPO }}:latest
-          docker push ${{ env.DOCKER_REPO_DEV }}:latest
-  lint:
-    needs: push
-    runs-on: self-hosted
-    environment:
-      name: staging
-    steps:
-      - name: Kubernetes - switch to staging context
-        run: |
-          kubectl config use-context staging
-      - name: Kubernetes - run linter
-        run: |
-          VERSION=${{ env.DEPLOYMENT_VERSION }} \
-          REPOSITORY=${{ env.DOCKER_REPO_DEV }} \
-          envsubst < ops/on-premises/kubernetes/backend/admin/jobs/linting.yaml | kubectl apply -f -
-          ./ops/on-premises/kubernetes/utils/wait_for_job.sh admin-linting-${{ env.DEPLOYMENT_VERSION }}
-  analyse:
-    needs: push
-    runs-on: self-hosted
-    environment:
-      name: staging
-    steps:
-      - name: Kubernetes - switch to staging context
-        run: |
-          kubectl config use-context staging
-      - name: Kubernetes - run static analysis
-        run: |
-          VERSION=${{ env.DEPLOYMENT_VERSION }} \
-          REPOSITORY=${{ env.DOCKER_REPO_DEV }} \
-          envsubst < ops/on-premises/kubernetes/backend/admin/jobs/analyse.yaml | kubectl apply -f -
-          ./ops/on-premises/kubernetes/utils/wait_for_job.sh admin-code-analysis-${{ env.DEPLOYMENT_VERSION }}
-  deploy_staging:
-    if: github.event.ref == 'refs/heads/develop' || github.event.ref == 'refs/heads/master' 
-    needs: [lint, analyse]
-    runs-on: self-hosted
-    environment:
-      name: staging
-      url: https://stage-admin.eden-reich.com
-    steps:
-      - uses: actions/checkout@master
-      - name: Kubernetes - switch to staging context
-        run: |
-          kubectl config use-context staging
-      - name: Kubernetes - run database migrations
-        run: |
-          VERSION=${{ env.DEPLOYMENT_VERSION }} \
-          REPOSITORY=${{ env.DOCKER_REPO }} \
-          envsubst < ops/on-premises/kubernetes/backend/admin/jobs/migrations.yaml | kubectl apply -f -
-          ./ops/on-premises/kubernetes/utils/wait_for_job.sh admin-database-migration-${{ env.DEPLOYMENT_VERSION }}
-      - name: Kubernetes - create a new deployment
-        run: |
-          VERSION=${{ env.DEPLOYMENT_VERSION }} \
-          REPOSITORY=${{ env.DOCKER_REPO }} \
-          envsubst < ops/on-premises/kubernetes/backend/admin/deployment.yaml | kubectl apply -f -
-      - name: Kubernetes - wait for new deployment to be successfully rolled out
-        run: |
-          max_count=60
-          count=0
-          while [ true ]; do
-            if [[ $count -gt $max_count ]]; then
-              echo "===> Waited for too long for a successful rolled out green version, but something went wrong. Aborting..."
-              exit 1
-            fi
-            if [[ $(kubectl rollout status deploy/${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} --timeout=5s 2>/dev/null | grep 'successfully rolled out') ]]; then
-              echo "=====> Green deployment has been successfully rolled out. Continuing..."
-              break
-            fi
-            count=$((count+1))
-            echo "===> Green deployment ${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} is being rolled out...Waiting..."
-            sleep 1
-          done
-      - name: Kubernetes - apply horizontal pods autoscaling to new deployment
-        run: |
-          VERSION=${{ env.DEPLOYMENT_VERSION }} \
-          envsubst < ops/on-premises/kubernetes/backend/admin/hpa.yaml | kubectl apply -f -
-      - name: Kubernetes - switch LB to green deployment
-        run: |
-          VERSION=${{ env.DEPLOYMENT_VERSION }} \
-          envsubst < ops/on-premises/kubernetes/backend/admin/service.yaml | kubectl apply -f -
-      - name: Kubernetes - remove completed jobs
-        run: kubectl delete jobs $(kubectl get jobs | grep ${{ env.DEPLOYMENT_NAME }} | grep 1/1 | awk '{ print $1 }' | xargs) || true
+  #     - name: Kubernetes - add docker pull secrets if not exists
+  #       run: |
+  #         DOCKER_CONFIG_JSON=${{ secrets.DOCKER_CONFIG_JSON }} \
+  #         envsubst < ops/on-premises/kubernetes/secrets/container_registry.yaml | kubectl apply -f -
+  # build:
+  #   runs-on: self-hosted
+  #   needs: docker_login
+  #   steps:
+  #     - uses: actions/checkout@master
+  #     - name: Docker - build container image
+  #       run: |
+  #         docker build \
+  #           --target production \
+  #           --cache-from ${{ env.DOCKER_REPO }}:latest \
+  #           -t ${{ env.DOCKER_REPO }}:latest \
+  #           -f ops/on-premises/docker/backend/admin/Dockerfile .
+  #     - name: Docker - build test container image
+  #       run: |
+  #         docker build \
+  #           --target src-with-devtools \
+  #           --cache-from ${{ env.DOCKER_REPO_DEV }}:latest \
+  #           -t ${{ env.DOCKER_REPO_DEV }}:latest \
+  #           -f ops/on-premises/docker/backend/admin/Dockerfile .
+  #     - name: Docker - tag container images
+  #       run: |
+  #         docker tag ${{ env.DOCKER_REPO }}:latest ${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }}
+  #         docker tag ${{ env.DOCKER_REPO_DEV }}:latest ${{ env.DOCKER_REPO_DEV }}:${{ env.DEPLOYMENT_VERSION }}
+  # push:
+  #   needs: build
+  #   runs-on: self-hosted
+  #   steps:
+  #     - name: Docker - push image to registry
+  #       run: |
+  #         docker push ${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }}
+  #         docker push ${{ env.DOCKER_REPO_DEV }}:${{ env.DEPLOYMENT_VERSION }}
+  #         docker push ${{ env.DOCKER_REPO }}:latest
+  #         docker push ${{ env.DOCKER_REPO_DEV }}:latest
+  # lint:
+  #   needs: push
+  #   runs-on: self-hosted
+  #   environment:
+  #     name: staging
+  #   steps:
+  #     - name: Kubernetes - switch to staging context
+  #       run: |
+  #         kubectl config use-context staging
+  #     - name: Kubernetes - run linter
+  #       run: |
+  #         VERSION=${{ env.DEPLOYMENT_VERSION }} \
+  #         REPOSITORY=${{ env.DOCKER_REPO_DEV }} \
+  #         envsubst < ops/on-premises/kubernetes/backend/admin/jobs/linting.yaml | kubectl apply -f -
+  #         ./ops/on-premises/kubernetes/utils/wait_for_job.sh admin-linting-${{ env.DEPLOYMENT_VERSION }}
+  # analyse:
+  #   needs: push
+  #   runs-on: self-hosted
+  #   environment:
+  #     name: staging
+  #   steps:
+  #     - name: Kubernetes - switch to staging context
+  #       run: |
+  #         kubectl config use-context staging
+  #     - name: Kubernetes - run static analysis
+  #       run: |
+  #         VERSION=${{ env.DEPLOYMENT_VERSION }} \
+  #         REPOSITORY=${{ env.DOCKER_REPO_DEV }} \
+  #         envsubst < ops/on-premises/kubernetes/backend/admin/jobs/analyse.yaml | kubectl apply -f -
+  #         ./ops/on-premises/kubernetes/utils/wait_for_job.sh admin-code-analysis-${{ env.DEPLOYMENT_VERSION }}
+  # deploy_staging:
+  #   if: github.event.ref == 'refs/heads/develop' || github.event.ref == 'refs/heads/master' 
+  #   needs: [lint, analyse]
+  #   runs-on: self-hosted
+  #   environment:
+  #     name: staging
+  #     url: https://stage-admin.eden-reich.com
+  #   steps:
+  #     - uses: actions/checkout@master
+  #     - name: Kubernetes - switch to staging context
+  #       run: |
+  #         kubectl config use-context staging
+  #     - name: Kubernetes - run database migrations
+  #       run: |
+  #         VERSION=${{ env.DEPLOYMENT_VERSION }} \
+  #         REPOSITORY=${{ env.DOCKER_REPO }} \
+  #         envsubst < ops/on-premises/kubernetes/backend/admin/jobs/migrations.yaml | kubectl apply -f -
+  #         ./ops/on-premises/kubernetes/utils/wait_for_job.sh admin-database-migration-${{ env.DEPLOYMENT_VERSION }}
+  #     - name: Kubernetes - create a new deployment
+  #       run: |
+  #         VERSION=${{ env.DEPLOYMENT_VERSION }} \
+  #         REPOSITORY=${{ env.DOCKER_REPO }} \
+  #         envsubst < ops/on-premises/kubernetes/backend/admin/deployment.yaml | kubectl apply -f -
+  #     - name: Kubernetes - wait for new deployment to be successfully rolled out
+  #       run: |
+  #         max_count=60
+  #         count=0
+  #         while [ true ]; do
+  #           if [[ $count -gt $max_count ]]; then
+  #             echo "===> Waited for too long for a successful rolled out green version, but something went wrong. Aborting..."
+  #             exit 1
+  #           fi
+  #           if [[ $(kubectl rollout status deploy/${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} --timeout=5s 2>/dev/null | grep 'successfully rolled out') ]]; then
+  #             echo "=====> Green deployment has been successfully rolled out. Continuing..."
+  #             break
+  #           fi
+  #           count=$((count+1))
+  #           echo "===> Green deployment ${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} is being rolled out...Waiting..."
+  #           sleep 1
+  #         done
+  #     - name: Kubernetes - apply horizontal pods autoscaling to new deployment
+  #       run: |
+  #         VERSION=${{ env.DEPLOYMENT_VERSION }} \
+  #         envsubst < ops/on-premises/kubernetes/backend/admin/hpa.yaml | kubectl apply -f -
+  #     - name: Kubernetes - switch LB to green deployment
+  #       run: |
+  #         VERSION=${{ env.DEPLOYMENT_VERSION }} \
+  #         envsubst < ops/on-premises/kubernetes/backend/admin/service.yaml | kubectl apply -f -
+  #     - name: Kubernetes - remove completed jobs
+  #       run: kubectl delete jobs $(kubectl get jobs | grep ${{ env.DEPLOYMENT_NAME }} | grep 1/1 | awk '{ print $1 }' | xargs) || true
   # deploy_production:
   #   needs: deploy_staging
   #   runs-on: self-hosted
