add additional steps for reverting and deploy to production

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -47,6 +47,24 @@ jobs:
         run: |
           DOCKER_CONFIG_JSON=${{ secrets.DOCKER_CONFIG_JSON }} \
           envsubst < ops/on-premises/kubernetes/secrets/container_registry.yaml | kubectl apply -f -
+  update_secrets_production:
+    runs-on: self-hosted
+    environment:
+      name: production
+    steps:
+      - uses: actions/checkout@master
+      - name: Kubernetes - switch to production context
+        run: |
+          kubectl config use-context production
+      - name: Kubernetes - update secrets in the cluster
+        run: |
+          FRONTEND_MAILGUN_API_KEY=${{ secrets.FRONTEND_MAILGUN_API_KEY }} \
+          FRONTEND_MAILGUN_DOMAIN=${{ secrets.FRONTEND_MAILGUN_DOMAIN }} \
+          envsubst < ops/on-premises/kubernetes/secrets/frontend.yaml | kubectl apply -f -
+      - name: Kubernetes - add docker pull secrets if not exists
+        run: |
+          DOCKER_CONFIG_JSON=${{ secrets.DOCKER_CONFIG_JSON }} \
+          envsubst < ops/on-premises/kubernetes/secrets/container_registry.yaml | kubectl apply -f -
   check:
     outputs:
       run_job: ${{ steps.check_files.outputs.run_job }}
@@ -138,6 +156,66 @@ jobs:
       - name: Kubernetes - switch LB to green deployment
         run: |
           VERSION=${{ env.DEPLOYMENT_VERSION }} \
+          envsubst < ops/on-premises/kubernetes/frontend/service.yaml | kubectl apply -f -
+  deploy_production:
+    needs: deploy_staging
+    if: github.event.ref == 'refs/heads/master'
+    runs-on: self-hosted
+    environment:
+      name: production
+      url: https://www.eden-reich.com
+    steps:
+      - uses: actions/checkout@master
+      - name: Kubernetes - switch to production context
+        run: |
+          kubectl config use-context production
+      - name: Kubernetes - create a new deployment
+        run: |
+          VERSION=${{ env.DEPLOYMENT_VERSION }} \
+          REPOSITORY=${{ env.DOCKER_REPO }} \
+          envsubst < ops/on-premises/kubernetes/frontend/deployment.yaml | kubectl apply -f -
+      - name: Kubernetes - wait for new deployment to be successfully rolled out
+        run: |
+          max_count=60
+          count=0
+          while [ true ]; do
+            if [[ $count -gt $max_count ]]; then
+              echo "===> Waited for too long for a successful rolled out green version, but something went wrong. Aborting..."
+              exit 1
+            fi
+            if [[ $(kubectl rollout status deploy/${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} --timeout=5s 2>/dev/null | grep 'successfully rolled out') ]]; then
+              echo "=====> Green deployment has been successfully rolled out. Continuing..."
+              break
+            fi
+            count=$((count+1))
+            echo "===> Green deployment ${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} is being rolled out...Waiting..."
+            sleep 1
+          done
+      - name: Kubernetes - apply horizontal pods autoscaling to new deployment
+        run: |
+          VERSION=${{ env.DEPLOYMENT_VERSION }} \
+          envsubst < ops/on-premises/kubernetes/frontend/hpa.yaml | kubectl apply -f -
+      - name: Kubernetes - switch LB to green deployment
+        run: |
+          VERSION=${{ env.DEPLOYMENT_VERSION }} \
+          envsubst < ops/on-premises/kubernetes/frontend/service.yaml | kubectl apply -f -
+  revert_production:
+    needs: deploy_production
+    runs-on: self-hosted
+    environment:
+      name: production
+      url: https://www.eden-reich.com
+    steps:
+      - name: Kubernetes - switch to production context
+        run: |
+          kubectl config use-context production
+      - name: Kubernetes - apply horizontal pods autoscaling to previous deployment
+        run: |
+          VERSION=${{ env.DEPLOYMENT_PREVIOUS_VERSION }} \
+          envsubst < ops/on-premises/kubernetes/frontend/hpa.yaml | kubectl apply -f -
+      - name: Kubernetes - switch LB to previous deployment
+        run: |
+          VERSION=${{ env.DEPLOYMENT_PREVIOUS_VERSION }} \
           envsubst < ops/on-premises/kubernetes/frontend/service.yaml | kubectl apply -f -
   cleanup:
     runs-on: self-hosted
