fix checkout annotation bug, just clone depth 0

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -32,113 +32,132 @@ jobs:
     environment:
       name: staging
     steps:
-      - uses: actions/checkout@master
-      - name: Kubernetes - switch to staging context
-        run: |
-          kubectl config use-context staging
-      - name: Kubernetes - update configmap in the cluster
-        run: |
-          APP_ENV=staging \
-          envsubst < frontend/config.yaml | kubectl apply -f -
+    - name: Checkout
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+    - name: Kubernetes - switch to staging context
+      run: |
+        kubectl config use-context staging
+    - name: Kubernetes - update configmap in the cluster
+      run: |
+        APP_ENV=staging \
+        envsubst < frontend/config.yaml | kubectl apply -f -
   update_configuration_production:
     if: github.event.ref == 'refs/heads/master'
     runs-on: self-hosted
     environment:
       name: production
     steps:
-      - uses: actions/checkout@master
-      - name: Kubernetes - switch to production context
-        run: |
-          kubectl config use-context production
-      - name: Kubernetes - update configmap in the cluster
-        run: |
-          APP_ENV=production \
-          envsubst < frontend/config.yaml | kubectl apply -f -
+    - name: Checkout
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+    - name: Kubernetes - switch to production context
+      run: |
+        kubectl config use-context production
+    - name: Kubernetes - update configmap in the cluster
+      run: |
+        APP_ENV=production \
+        envsubst < frontend/config.yaml | kubectl apply -f -
   update_secrets_staging:
     runs-on: self-hosted
     environment:
       name: staging
     steps:
-      - uses: actions/checkout@master
-      - name: Kubernetes - switch to staging context
-        run: |
-          kubectl config use-context staging
-      - name: Kubernetes - update secrets in the cluster
-        run: |
-          API_USERNAME=${{ secrets.FRONTEND_API_USERNAME }} \
-          API_PASSWORD=${{ secrets.FRONTEND_API_PASSWORD }} \
-          MAILGUN_API_KEY=${{ secrets.FRONTEND_MAILGUN_API_KEY }} \
-          MAILGUN_DOMAIN=${{ secrets.FRONTEND_MAILGUN_DOMAIN }} \
-          envsubst < frontend/secret.yaml | kubectl apply -f -
-      - name: Kubernetes - add docker pull secrets if not exists
-        run: |
-          DOCKER_CONFIG_JSON=${{ secrets.DOCKER_CONFIG_JSON }} \
-          envsubst < ops/on-premises/kubernetes/secrets/container_registry.yaml | kubectl apply -f -
+    - name: Checkout
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+    - name: Kubernetes - switch to staging context
+      run: |
+        kubectl config use-context staging
+    - name: Kubernetes - update secrets in the cluster
+      run: |
+        API_USERNAME=${{ secrets.FRONTEND_API_USERNAME }} \
+        API_PASSWORD=${{ secrets.FRONTEND_API_PASSWORD }} \
+        MAILGUN_API_KEY=${{ secrets.FRONTEND_MAILGUN_API_KEY }} \
+        MAILGUN_DOMAIN=${{ secrets.FRONTEND_MAILGUN_DOMAIN }} \
+        envsubst < frontend/secret.yaml | kubectl apply -f -
+    - name: Kubernetes - add docker pull secrets if not exists
+      run: |
+        DOCKER_CONFIG_JSON=${{ secrets.DOCKER_CONFIG_JSON }} \
+        envsubst < ops/on-premises/kubernetes/secrets/container_registry.yaml | kubectl apply -f -
   update_secrets_production:
     if: github.event.ref == 'refs/heads/master'
     runs-on: self-hosted
     environment:
       name: production
     steps:
-      - uses: actions/checkout@master
-      - name: Kubernetes - switch to production context
-        run: |
-          kubectl config use-context production
-      - name: Kubernetes - update secrets in the cluster
-        run: |
-          API_USERNAME=${{ secrets.FRONTEND_API_USERNAME }} \
-          API_PASSWORD=${{ secrets.FRONTEND_API_PASSWORD }} \
-          MAILGUN_API_KEY=${{ secrets.FRONTEND_MAILGUN_API_KEY }} \
-          MAILGUN_DOMAIN=${{ secrets.FRONTEND_MAILGUN_DOMAIN }} \
-          envsubst < frontend/secret.yaml | kubectl apply -f -
-      - name: Kubernetes - add docker pull secrets if not exists
-        run: |
-          DOCKER_CONFIG_JSON=${{ secrets.DOCKER_CONFIG_JSON }} \
-          envsubst < ops/on-premises/kubernetes/secrets/container_registry.yaml | kubectl apply -f -
+    - name: Checkout
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+    - name: Kubernetes - switch to production context
+      run: |
+        kubectl config use-context production
+    - name: Kubernetes - update secrets in the cluster
+      run: |
+        API_USERNAME=${{ secrets.FRONTEND_API_USERNAME }} \
+        API_PASSWORD=${{ secrets.FRONTEND_API_PASSWORD }} \
+        MAILGUN_API_KEY=${{ secrets.FRONTEND_MAILGUN_API_KEY }} \
+        MAILGUN_DOMAIN=${{ secrets.FRONTEND_MAILGUN_DOMAIN }} \
+        envsubst < frontend/secret.yaml | kubectl apply -f -
+    - name: Kubernetes - add docker pull secrets if not exists
+      run: |
+        DOCKER_CONFIG_JSON=${{ secrets.DOCKER_CONFIG_JSON }} \
+        envsubst < ops/on-premises/kubernetes/secrets/container_registry.yaml | kubectl apply -f -
   check:
     outputs:
       run_job: ${{ steps.check_files.outputs.run_job }}
     runs-on: self-hosted
     steps:
-      - uses: actions/checkout@master
-        with:
-          fetch-depth: 2
-      - name: Check if relevant artifact files have been changed
-        id: check_files
-        run: |
-          for file in $(echo ${{ env.ARTIFACT_FILES }} | xargs); do
-            if [ $(git diff --name-only HEAD^ HEAD | grep $file) ]; then 
-              echo "::set-output name=run_job::true"
-              break
-            else
-              echo "::set-output name=run_job::false"
-            fi
-          done
+    - name: Checkout
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+    - name: Check if relevant artifact files have been changed
+      id: check_files
+      run: |
+        for file in $(echo ${{ env.ARTIFACT_FILES }} | xargs); do
+          if [ $(git diff --name-only HEAD^ HEAD | grep $file) ]; then 
+            echo "::set-output name=run_job::true"
+            break
+          else
+            echo "::set-output name=run_job::false"
+          fi
+        done
   build-artifacts:
     needs: check
     runs-on: self-hosted
     steps:
-      - uses: actions/checkout@master
-      - name: Docker - build artifacts
-        if: ${{ needs.check.outputs.run_job == 'true' }}
-        run: |
-          docker build \
-            --target frontend-artifacts \
-            -t frontend-artifacts:latest \
-            -f frontend/Dockerfile .
+    - name: Checkout
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+    - name: Docker - build artifacts
+      if: ${{ needs.check.outputs.run_job == 'true' }}
+      run: |
+        docker build \
+          --target frontend-artifacts \
+          -t frontend-artifacts:latest \
+          -f frontend/Dockerfile .
   build:
     needs: [build-artifacts]
     runs-on: self-hosted
     steps:
-      - uses: actions/checkout@master
-      - name: Docker - build container image
-        run: |
-          docker build \
-            --target production \
-            --cache-from ${{ env.DOCKER_REPO }}:latest \
-            -t ${{ env.DOCKER_REPO }}:latest \
-            -t ${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }} \
-            -f frontend/Dockerfile .
+    - name: Checkout
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+    - name: Docker - build container image
+      run: |
+        docker build \
+          --target production \
+          --cache-from ${{ env.DOCKER_REPO }}:latest \
+          -t ${{ env.DOCKER_REPO }}:latest \
+          -t ${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }} \
+          -f frontend/Dockerfile .
   push:
     needs: [build, docker_login]
     runs-on: self-hosted
@@ -154,40 +173,43 @@ jobs:
       name: staging
       url: https://stage.eden-reich.com
     steps:
-      - uses: actions/checkout@master
-      - name: Kubernetes - switch to staging context
-        run: |
-          kubectl config use-context staging
-      - name: Kubernetes - create a new deployment
-        run: |
-          VERSION=${{ env.DEPLOYMENT_VERSION }} \
-          REPOSITORY=${{ env.DOCKER_REPO }} \
-          envsubst < frontend/deployment.yaml | kubectl apply -f -
-      - name: Kubernetes - wait for new deployment to be successfully rolled out
-        run: |
-          max_count=60
-          count=0
-          while [ true ]; do
-            if [[ $count -gt $max_count ]]; then
-              echo "===> Waited for too long for a successful rolled out green version, but something went wrong. Aborting..."
-              exit 1
-            fi
-            if [[ $(kubectl rollout status deploy/${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} --timeout=5s 2>/dev/null | grep 'successfully rolled out') ]]; then
-              echo "=====> Green deployment has been successfully rolled out. Continuing..."
-              break
-            fi
-            count=$((count+1))
-            echo "===> Green deployment ${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} is being rolled out...Waiting..."
-            sleep 1
-          done
-      - name: Kubernetes - apply horizontal pods autoscaling to new deployment
-        run: |
-          VERSION=${{ env.DEPLOYMENT_VERSION }} \
-          envsubst < frontend/hpa.yaml | kubectl apply -f -
-      - name: Kubernetes - switch LB to green deployment
-        run: |
-          VERSION=${{ env.DEPLOYMENT_VERSION }} \
-          envsubst < frontend/service.yaml | kubectl apply -f -
+    - name: Checkout
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+    - name: Kubernetes - switch to staging context
+      run: |
+        kubectl config use-context staging
+    - name: Kubernetes - create a new deployment
+      run: |
+        VERSION=${{ env.DEPLOYMENT_VERSION }} \
+        REPOSITORY=${{ env.DOCKER_REPO }} \
+        envsubst < frontend/deployment.yaml | kubectl apply -f -
+    - name: Kubernetes - wait for new deployment to be successfully rolled out
+      run: |
+        max_count=60
+        count=0
+        while [ true ]; do
+          if [[ $count -gt $max_count ]]; then
+            echo "===> Waited for too long for a successful rolled out green version, but something went wrong. Aborting..."
+            exit 1
+          fi
+          if [[ $(kubectl rollout status deploy/${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} --timeout=5s 2>/dev/null | grep 'successfully rolled out') ]]; then
+            echo "=====> Green deployment has been successfully rolled out. Continuing..."
+            break
+          fi
+          count=$((count+1))
+          echo "===> Green deployment ${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} is being rolled out...Waiting..."
+          sleep 1
+        done
+    - name: Kubernetes - apply horizontal pods autoscaling to new deployment
+      run: |
+        VERSION=${{ env.DEPLOYMENT_VERSION }} \
+        envsubst < frontend/hpa.yaml | kubectl apply -f -
+    - name: Kubernetes - switch LB to green deployment
+      run: |
+        VERSION=${{ env.DEPLOYMENT_VERSION }} \
+        envsubst < frontend/service.yaml | kubectl apply -f -
   deploy_production:
     needs: deploy_staging
     if: github.event.ref == 'refs/heads/master'
@@ -196,40 +218,43 @@ jobs:
       name: production
       url: https://www.eden-reich.com
     steps:
-      - uses: actions/checkout@master
-      - name: Kubernetes - switch to production context
-        run: |
-          kubectl config use-context production
-      - name: Kubernetes - create a new deployment
-        run: |
-          VERSION=${{ env.DEPLOYMENT_VERSION }} \
-          REPOSITORY=${{ env.DOCKER_REPO }} \
-          envsubst < frontend/deployment.yaml | kubectl apply -f -
-      - name: Kubernetes - wait for new deployment to be successfully rolled out
-        run: |
-          max_count=60
-          count=0
-          while [ true ]; do
-            if [[ $count -gt $max_count ]]; then
-              echo "===> Waited for too long for a successful rolled out green version, but something went wrong. Aborting..."
-              exit 1
-            fi
-            if [[ $(kubectl rollout status deploy/${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} --timeout=5s 2>/dev/null | grep 'successfully rolled out') ]]; then
-              echo "=====> Green deployment has been successfully rolled out. Continuing..."
-              break
-            fi
-            count=$((count+1))
-            echo "===> Green deployment ${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} is being rolled out...Waiting..."
-            sleep 1
-          done
-      - name: Kubernetes - apply horizontal pods autoscaling to new deployment
-        run: |
-          VERSION=${{ env.DEPLOYMENT_VERSION }} \
-          envsubst < frontend/hpa.yaml | kubectl apply -f -
-      - name: Kubernetes - switch LB to green deployment
-        run: |
-          VERSION=${{ env.DEPLOYMENT_VERSION }} \
-          envsubst < frontend/service.yaml | kubectl apply -f -
+    - name: Checkout
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+    - name: Kubernetes - switch to production context
+      run: |
+        kubectl config use-context production
+    - name: Kubernetes - create a new deployment
+      run: |
+        VERSION=${{ env.DEPLOYMENT_VERSION }} \
+        REPOSITORY=${{ env.DOCKER_REPO }} \
+        envsubst < frontend/deployment.yaml | kubectl apply -f -
+    - name: Kubernetes - wait for new deployment to be successfully rolled out
+      run: |
+        max_count=60
+        count=0
+        while [ true ]; do
+          if [[ $count -gt $max_count ]]; then
+            echo "===> Waited for too long for a successful rolled out green version, but something went wrong. Aborting..."
+            exit 1
+          fi
+          if [[ $(kubectl rollout status deploy/${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} --timeout=5s 2>/dev/null | grep 'successfully rolled out') ]]; then
+            echo "=====> Green deployment has been successfully rolled out. Continuing..."
+            break
+          fi
+          count=$((count+1))
+          echo "===> Green deployment ${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} is being rolled out...Waiting..."
+          sleep 1
+        done
+    - name: Kubernetes - apply horizontal pods autoscaling to new deployment
+      run: |
+        VERSION=${{ env.DEPLOYMENT_VERSION }} \
+        envsubst < frontend/hpa.yaml | kubectl apply -f -
+    - name: Kubernetes - switch LB to green deployment
+      run: |
+        VERSION=${{ env.DEPLOYMENT_VERSION }} \
+        envsubst < frontend/service.yaml | kubectl apply -f -
   revert_production:
     needs: deploy_production
     runs-on: self-hosted
